package com.albatross.sensor.sim.core;

/**
 * Base interface on which entire API works An object/device used to measure any quantifiable physical/chemical or biological phenomenon.
 * @author iamrp 
 * 
 *
 */
public interface Measurer {

    /**
     * @return Type, Make and unit of measurements based on which measurement is
     * taken
     */
    public Type getType();

    /**
     *
     * @return the next value generated by the measurable object
     */
    public Quantity<?> generateNextQuantity();

    /**
     *
     * @return the last recorded value of measurable object
     */
    public Quantity<?> getQuantity();

}
